// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfLFLbMvG1PNNEQyKowXD8XBuwkrbZxo',
    appId: '1:32030000640:web:0a8207728d28fea93efae5',
    messagingSenderId: '32030000640',
    projectId: 'calculadora-de-lixo',
    authDomain: 'calculadora-de-lixo.firebaseapp.com',
    storageBucket: 'calculadora-de-lixo.appspot.com',
    measurementId: 'G-N3QHTS3D9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOL9iDhyEerzaPFhJx5ZFliFs21wR9K0w',
    appId: '1:32030000640:android:e84753b7f2ba45d93efae5',
    messagingSenderId: '32030000640',
    projectId: 'calculadora-de-lixo',
    storageBucket: 'calculadora-de-lixo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohq5grZ8gIoxsRTyFSQASWHs9N4PHw_4',
    appId: '1:32030000640:ios:e2c6d6363ad3594b3efae5',
    messagingSenderId: '32030000640',
    projectId: 'calculadora-de-lixo',
    storageBucket: 'calculadora-de-lixo.appspot.com',
    iosBundleId: 'com.example.calculadoraDeLixo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohq5grZ8gIoxsRTyFSQASWHs9N4PHw_4',
    appId: '1:32030000640:ios:e2c6d6363ad3594b3efae5',
    messagingSenderId: '32030000640',
    projectId: 'calculadora-de-lixo',
    storageBucket: 'calculadora-de-lixo.appspot.com',
    iosBundleId: 'com.example.calculadoraDeLixo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSfLFLbMvG1PNNEQyKowXD8XBuwkrbZxo',
    appId: '1:32030000640:web:41d0dcfb544761e83efae5',
    messagingSenderId: '32030000640',
    projectId: 'calculadora-de-lixo',
    authDomain: 'calculadora-de-lixo.firebaseapp.com',
    storageBucket: 'calculadora-de-lixo.appspot.com',
    measurementId: 'G-WJHN1ZME1K',
  );
}
